ansible_host: 172.16.119.128
ansible_user: admin1
ansible_password: admin
ansible_become_pass: admin
ansible_ssh_private_key_file: ~/.ssh/ansible_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
